DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS GAMES;
DROP TABLE IF EXISTS COMMANDS;

CREATE TABLE USERS (
	userid INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, 
	username TEXT NOT NULL UNIQUE, 
	password TEXT NOT NULL, 
);

CREATE TABLE GAMES (
	gameid INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
	initgameblob TEXT,
	currgameblob TEXT
);

CREATE TABLE COMMANDS (
	commandid INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
	cmdblob TEXT,
	gameid INTEGER NOT NULL
);

